### ISSUE TITLE
refactor customizing of color codes

### ISSUE THREAD

**Issue by rosabraatz** [mammooc/RatingWidget#1]
- define color-scheme classes in rating-widget.html
- custom variable is a string which should evaluate the corresponding class via javascript
- javascript evaluation: define an observer in properties for custom variable
- observer will call javascript function whenever variables has changed
- color-scheme class will define color codes for polymer components

**Comment by Atyanar** [comment]
another alternative would be to allow up to three colors as properties which are used by the widget.
