### ISSUE TITLE
Move rating-stars to own element?

### ISSUE THREAD

**Issue by PFischbeck** [mammooc/RatingWidget#3]
Should the rating-stars be moved to its own repository? It is independent of the ratingWidget, and this would allow for others to use the component.

**Comment by MrSerth** [comment]
I am fine with creating another repo, but as I am not deeply involved into that discussion, feel free to decide without my consent. Any owner of the organization can create new repositories and grant access rights.

**Comment by Atyanar** [comment]
rating-stars now has its own repository called awesome-rating.
