### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by PFischbeck** [mammooc/RatingWidget#4]
If we want the component to be used by different providers, i18n might be an important issue.

There are a number of i18n components, e.g.
https://ebidel.github.io/i18n-msg/components/i18n-msg/

**Comment by Atyanar** [comment]
According to Jan:
We should check whether we can access the 'current locale' attribute of the provider, if not then we should just create a property that the provider has to set. The fallback should be English.
(We can ask Steffi for the more unusual translations like Chinese).

**Comment by MrSerth** [comment]
Could you please provide us with some information how we pass the `current locale` attribute? I can't find anything related to that in the docs.

**Comment by PFischbeck** [comment]
Currently, the locale can not be passed to the component, but it is set to the language of the including page per default. Should this be changed? Should there be an optional attribute to set the language?

**Comment by MrSerth** [comment]
I don't know whether we need this attribute to correctly embed the widget to our beach head platform. I could try that later on with the newest version.

**Comment by MrSerth** [comment]
As we say that everything works fine, I'll close the issue right now.
