### ISSUE TITLE
Set up github pages (documentation)

### ISSUE THREAD

**Issue by Atyanar** [mammooc/RatingWidget#7]

**Comment by MrSerth** [comment]
We might want to use the Wiki as well...

**Comment by PFischbeck** [comment]
We could autodeploy to github pages whenever the master changes, see
https://github.com/steveklabnik/automatically_update_github_pages_with_travis_example
and 
https://www.polymer-project.org/1.0/docs/tools/reusable-elements#publishing-a-demo-and-landing-page-for-your-element
